import React from 'react';
import "./style.scss";

const Cgv = () => (
  <div className="cgv">
    <h2 className="cgv-title">Nos conditions générales de ventes et Rgpd</h2>
    <div className="cgv-paragraph">
      <h3 className="cgv-paragraph-title" id="cgv">Les cgv</h3>
      <p className="cgv-paragraph-text">Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex, molestias accusamus. Doloribus ratione tempora, deleniti illo adipisci a quos, qui pariatur assumenda accusantium dolorum voluptates sit cupiditate nisi voluptatum perferendis veritatis est natus unde reiciendis id ad cumque? Ipsam, cupiditate necessitatibus quam natus itaque aut illum aliquid libero ab corporis beatae inventore labore, debitis cumque commodi dolorem fugiat minima suscipit pariatur incidunt optio. Iste nobis aliquid illo ea facere fuga magnam ex earum autem deleniti! Tempore rem, consequatur nihil fugiat perferendis velit hic quae aspernatur suscipit, minus molestias provident sequi atque beatae dolores quibusdam repudiandae? Veniam harum tenetur nulla provident beatae magnam explicabo, iste voluptas quas consequuntur repudiandae laudantium impedit voluptate iure nostrum soluta. Dolore maxime quis aliquam ex, nobis sit dolorum inventore similique, cumque neque provident sint sapiente sunt! Numquam, enim? Itaque qui nesciunt nobis esse atque natus nisi iure aut sit quam. Consequuntur mollitia ipsum optio magni architecto corrupti voluptatum laudantium eos, rem laboriosam. Totam voluptatibus sint optio dolorum animi aliquam eaque esse eligendi, quas sit dicta dolorem maiores illum doloremque! Quas magnam facilis deserunt nesciunt! Ducimus similique culpa eum provident est, laborum, libero, quos ad atque maiores repellendus illum? Quo suscipit cupiditate esse illum minus voluptate harum est, itaque amet, sunt voluptatum quam consectetur a veniam molestias, natus ducimus quas ab accusantium ipsam quod neque quidem enim facere. Labore, sit id ad temporibus neque ducimus voluptatum rerum nihil, earum unde cum facere nulla ab ex laborum, corrupti soluta? Cum porro quisquam culpa, quam quia fuga inventore eveniet cupiditate dolorem voluptates incidunt alias repellat repudiandae in. Quam delectus repudiandae dicta temporibus. Doloremque, nobis harum quidem excepturi velit dolores aliquam dolorum exercitationem nesciunt repellendus deleniti facere nulla! Rem suscipit ullam qui iure reiciendis sapiente, culpa itaque at asperiores quod veniam omnis quos dolor impedit perspiciatis totam saepe! Aspernatur, veniam.</p>
    </div>
    <div className="cgv-paragraph">
      <h3 className="cgv-paragraph-title" id="rgpd">La rgpd</h3>
      <p className="cgv-paragraph-text">Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex, molestias accusamus. Doloribus ratione tempora, deleniti illo adipisci a quos, qui pariatur assumenda accusantium dolorum voluptates sit cupiditate nisi voluptatum perferendis veritatis est natus unde reiciendis id ad cumque? Ipsam, cupiditate necessitatibus quam natus itaque aut illum aliquid libero ab corporis beatae inventore labore, debitis cumque commodi dolorem fugiat minima suscipit pariatur incidunt optio. Iste nobis aliquid illo ea facere fuga magnam ex earum autem deleniti! Tempore rem, consequatur nihil fugiat perferendis velit hic quae aspernatur suscipit, minus molestias provident sequi atque beatae dolores quibusdam repudiandae? Veniam harum tenetur nulla provident beatae magnam explicabo, iste voluptas quas consequuntur repudiandae laudantium impedit voluptate iure nostrum soluta. Dolore maxime quis aliquam ex, nobis sit dolorum inventore similique, cumque neque provident sint sapiente sunt! Numquam, enim? Itaque qui nesciunt nobis esse atque natus nisi iure aut sit quam. Consequuntur mollitia ipsum optio magni architecto corrupti voluptatum laudantium eos, rem laboriosam. Totam voluptatibus sint optio dolorum animi aliquam eaque esse eligendi, quas sit dicta dolorem maiores illum doloremque! Quas magnam facilis deserunt nesciunt! Ducimus similique culpa eum provident est, laborum, libero, quos ad atque maiores repellendus illum? Quo suscipit cupiditate esse illum minus voluptate harum est, itaque amet, sunt voluptatum quam consectetur a veniam molestias, natus ducimus quas ab accusantium ipsam quod neque quidem enim facere. Labore, sit id ad temporibus neque ducimus voluptatum rerum nihil, earum unde cum facere nulla ab ex laborum, corrupti soluta? Cum porro quisquam culpa, quam quia fuga inventore eveniet cupiditate dolorem voluptates incidunt alias repellat repudiandae in. Quam delectus repudiandae dicta temporibus. Doloremque, nobis harum quidem excepturi velit dolores aliquam dolorum exercitationem nesciunt repellendus deleniti facere nulla! Rem suscipit ullam qui iure reiciendis sapiente, culpa itaque at asperiores quod veniam omnis quos dolor impedit perspiciatis totam saepe! Aspernatur, veniam.</p>
    </div>
  </div>
);

export default Cgv;
